
POST https://thawing-river-00445.herokuapp.com/api/user/signup
Content-Type: application/json

{  
    "name":"kumaresshneww",
    "email":"kums@gmsmm",
    "phone":"85446822s22",
    "password":"fffsf",
    "userId":"dddss"
}
###


GET http://localhost:8080/api/user/getuser
Content-Type: application/json

{
    "userId":"ddd"
}
###


###


POST http://localhost:8080/api/user/getuser
Content-Type: application/json

{
    "userid":"36456b4a2d557147714d7153"
}
###

###


POST http://localhost:8080/api/document/save
Content-Type: application/json

{
    "userid":"d",

    "document":{

            "name":"aadhar",
            "start_date":"1/12/9"
    }
}
###



GET http://localhost:8080/test/hello

