
POST http://localhost:8080/api/user/save
Content-Type: application/json

{  
    "name":"kumaresshneww",
    "email":"kums@gdmsmm",
    "phone":"8546822s22",
    "password":"fffsf"

}
###


GET http://localhost:8080/api/user/getuser
Content-Type: application/json

{
    "userId":"0dc0eb23-3eef-4590-9ac3-11d40c00133e"
}
###


###


###

###


POST http://localhost:8080/api/document/save
Content-Type: application/json

{
    "userId":"0dc0eb23-3eef-4590-9ac3-11d40c00133e",

    "document":{
        "imageUrl":"https://stackoverflow.com/questions/59525278/react-native-firebase-storage-get-url-after-uploading-an-image",
        "name":"License",
        "expiryDate":"12/12/2028",
        "description":"dccd"
            
    }
}
###
GET http://localhost:8080/api/document/getphone?phone=6385119226

###

POST http://localhost:8080/api/document/addfamily
Content-Type: application/json

{
     "userId": "4bb7cae9-b847-4172-904e-fb0d01079800",
        
        "familyMemberPhone": "1234567890"
}


###
GET http://localhost:8080/test/hello

###
PUT http://localhost:8080/api/user/updateuser
Content-Type: application/json

{
    "userId":"0dc0eb23-3eef-4590-9ac3-11d40c00133e",
    "newData":{
        "name": "kumaressh_Updated",
        "phone": "8546822122"

    }
}

